# --- Etapa 1: Construcción (Builder) ---
FROM node:18-alpine as builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# 1. Declara que esperas recibir estas variables (Mismos nombres que tu .env)
ARG VITE_TOOLRENT_BACKEND_SERVER
ARG VITE_TOOLRENT_BACKEND_PORT

# 2. Conviértelas en variables de entorno para que el build las vea
ENV VITE_TOOLRENT_BACKEND_SERVER=$VITE_TOOLRENT_BACKEND_SERVER
ENV VITE_TOOLRENT_BACKEND_PORT=$VITE_TOOLRENT_BACKEND_PORT

# Esto generará la carpeta /app/dist dentro del contenedor temporal
RUN npm run build

# --- Etapa 2: Servidor NGINX (Producción) ---
FROM nginx:stable-alpine

# Copiamos SOLO los archivos generados en la etapa anterior
# Nota el "--from=builder"
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]